"""HTTPS composition for one fixed independent dev pool; no runtime activation."""
from __future__ import annotations

import copy
import ssl
from dataclasses import asdict
from pathlib import Path
from typing import Any
from uuid import UUID

from scripts.ops import nebius_certificates as private_state
from scripts.ops.nebius_development_management_retained import load_retained_management
from scripts.ops.nebius_development_pool_intent import (
    DevelopmentPoolIntent,
    delivery_documents,
    namespace_documents,
    prepare_intent,
)
from scripts.ops.nebius_development_pool_registration import (
    DevelopmentPoolRegistrationRequest,
    register_development_pool,
)
from scripts.ops.nebius_development_pool_registration_live import (
    HTTPSDevelopmentPoolRegistrationAPI,
    HTTPSRetainedDevelopmentManagementAPI,
)
from scripts.ops.nebius_ingress_stage import _key, _snapshot, _uid
from scripts.ops.nebius_management_material import ManagementBinding
from scripts.ops.nebius_management_stage import (
    _MARKER,
    _comparison_snapshot,
    _defaulted,
    _stage_fixed_documents,
    _validate_record,
)
from scripts.ops.nebius_management_supplied import _defaulted as _secret_defaulted

from loom.nebius_platform_render import digest
from loom_service.environment_management.candidates import _json


class _PhaseAPI(HTTPSRetainedDevelopmentManagementAPI):
    """Only documents generated by the connected parent reach this adapter."""

    def __init__(self, *, parent: HTTPSDevelopmentPoolInstallAPI, documents: dict[str, dict[str, Any]],
                 namespaces: dict[str, dict[str, Any]]):
        super().__init__(retained=parent.retained, api_server=parent.api_server,
            ssl_context=parent.context, token=parent.token, private_files=parent.private_files)
        self.documents, self.namespaces = copy.deepcopy(documents), copy.deepcopy(namespaces)

    def verify_identity(self, binding: ManagementBinding) -> None:
        super().verify_identity(binding)
        for name, expected in self.namespaces.items():
            actual = self._request('GET', '/api/v1/namespaces/' + name)
            if actual is None or _uid(actual) != _uid(expected) or _snapshot(actual) != _snapshot(expected):
                raise ValueError('development pool namespace changed')

    def _approved(self, document: dict[str, Any], *, writing: bool = False) -> str:
        try:
            desired = copy.deepcopy(document)
            expected = self.documents[_key(desired)]
            annotations = desired['metadata'].get('annotations', {})
            operation = annotations.pop(_MARKER, None)
            if writing or operation is not None:
                if str(UUID(operation)) != operation or not UUID(operation).int:
                    raise ValueError()
            if not annotations and 'annotations' not in expected['metadata']:
                desired['metadata'].pop('annotations', None)
            if desired != expected:
                raise ValueError()
            kind = desired['kind']
            if kind == 'Namespace':
                return '/api/v1/namespaces'
            version, plural = {'Secret': ('v1', 'secrets'), 'ConfigMap': ('v1', 'configmaps'),
                'ServiceAccount': ('v1', 'serviceaccounts'), 'Deployment': ('apps/v1', 'deployments')}[kind]
            namespace = desired['metadata']['namespace']
            if desired['apiVersion'] != version or not isinstance(namespace, str):
                raise ValueError()
            return ('/api/v1' if version == 'v1' else '/apis/' + version) + '/namespaces/' + namespace + '/' + plural
        except Exception:
            raise ValueError('resource outside fixed development pool stage') from None


class HTTPSDevelopmentPoolInstallAPI(HTTPSRetainedDevelopmentManagementAPI):
    def __init__(self, *, intent: DevelopmentPoolIntent, api_server: str,
                 ssl_context: ssl.SSLContext, token: str | None = None,
                 private_files: dict[Path, bytes] | None = None):
        self.intent = prepare_intent(reference=intent.reference, catalog=intent.catalog, tokens=intent.tokens)
        self.context, self.token = ssl_context, token
        self.namespace_state: Path | None = None
        super().__init__(retained=load_retained_management(intent.reference), api_server=api_server,
            ssl_context=ssl_context, token=token, private_files=private_files)

    def qualify(self, intent: DevelopmentPoolIntent) -> None:
        if intent != self.intent:
            raise ValueError('development pool intent changed')
        self.verify_identity(self.binding)

    def _namespaces(self) -> dict[str, dict[str, Any]]:
        if self.namespace_state is None:
            raise ValueError('development pool namespaces not staged')
        self.inspect_namespaces(self.namespace_state)
        record = _json(private_state._private_read(self.namespace_state / 'stage.json', limit=4 * 1024**2))
        result = {}
        for item in record['resources'].values():
            if item['status'] != 'created':
                raise ValueError('development pool namespaces not complete')
            document = copy.deepcopy(item['observed'])
            document['metadata']['uid'] = item['uid']
            result[document['metadata']['name']] = document
        return result

    def inspect_namespaces(self, state: Path) -> None:
        documents = namespace_documents(self.intent)
        with _PhaseAPI(parent=self, documents=documents, namespaces={}) as api:
            api.verify_identity(self.binding)
            journal = state / 'stage.json'
            if not journal.exists() and not journal.is_symlink():
                if state.exists() or state.is_symlink() or any(api.get_resource(doc) is not None for doc in documents.values()):
                    raise ValueError('development pool namespaces untracked')
                return
            record = _json(private_state._private_read(journal, limit=4 * 1024**2))
            _validate_record(record, {'schema': 'loom.nebius-management-stage.v1', 'binding': asdict(self.binding),
                'revision': digest(documents), 'phase': 'development-pool-namespaces'}, documents)
            for item in record['resources'].values():
                actual = api.get_resource(item['desired'])
                if item['status'] == 'prepared':
                    if actual is not None:
                        raise ValueError()
                elif (actual is None or _comparison_snapshot(actual) != item['expected']
                        or (item['status'] == 'created' and (_uid(actual) != item['uid'] or _snapshot(actual) != item['observed']))):
                    raise ValueError('development pool namespace differs')
            api.verify_identity(self.binding)

    def stage_namespaces(self, state: Path) -> dict[str, str]:
        documents = namespace_documents(self.intent)
        with _PhaseAPI(parent=self, documents=documents, namespaces={}) as api:
            receipt = _stage_fixed_documents(documents=documents, revision=digest(documents),
                phase='development-pool-namespaces', binding=self.binding, api=api, state_dir=state)
        self.namespace_state = state
        return {doc['metadata']['name']: receipt['resource_uids'][key] for key, doc in documents.items()}

    def register(self, request: DevelopmentPoolRegistrationRequest) -> dict[str, Any]:
        self._namespaces()
        with HTTPSDevelopmentPoolRegistrationAPI(request=request, api_server=self.api_server,
                ssl_context=self.context, token=self.token, private_files=self.private_files) as api:
            result = register_development_pool(request=request, api=api, execute=True)
        self._namespaces()
        return result

    def deliver(self, request: DevelopmentPoolRegistrationRequest, phase: str, state: Path) -> None:
        documents = delivery_documents(self.intent, request)[phase]
        namespaces = self._namespaces()
        with _PhaseAPI(parent=self, documents=documents, namespaces=namespaces) as api:
            _stage_fixed_documents(documents=documents, revision=digest(documents), phase='development-pool-' + phase,
                binding=self.binding, api=api, state_dir=state,
                default_document=_secret_defaulted if phase == 'material' else _defaulted)

    def inspect_delivery(self, request: DevelopmentPoolRegistrationRequest, state: Path) -> None:
        """After all writes, requalify earlier credentials/configuration as well."""
        namespaces = self._namespaces()
        for phase, documents in delivery_documents(self.intent, request).items():
            record = _json(private_state._private_read(state / phase / 'stage.json', limit=4 * 1024**2))
            _validate_record(record, {'schema': 'loom.nebius-management-stage.v1', 'binding': asdict(self.binding),
                'revision': digest(documents), 'phase': 'development-pool-' + phase}, documents)
            with _PhaseAPI(parent=self, documents=documents, namespaces=namespaces) as api:
                api.verify_identity(self.binding)
                for item in record['resources'].values():
                    actual = api.get_resource(item['desired'])
                    if (item['status'] != 'created' or actual is None or _uid(actual) != item['uid']
                            or _snapshot(actual) != item['observed']):
                        raise ValueError('development pool material or runtime changed')
                api.verify_identity(self.binding)
